name: "Apply Stack after PR is Merged"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Run Terraform CDK
        uses: danielmschmidt/terraform-cdk-action@main
        with:
          terraformVersion: 1.0.7
          cdktfVersion: 0.11.1
          stackName: cdktf-github-actions-terraform-cloud
          mode: auto-approve-apply
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
